<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('trainee_forms', function (Blueprint $table) {
            $table->id();
            
            // 1-4: Personal Info
            $table->string('full_name');
            $table->string('email')->unique();
            $table->string('phone');
            $table->text('address');
            
            // 5-8: Academic
            $table->string('institution');
            $table->string('major');
            $table->string('study_level'); // diploma/degree/other
            $table->date('grad_date');
            
            // 9-12: Internship details
            $table->integer('duration');
            $table->date('start_date');
            $table->string('interest');
            $table->string('coursework_req'); // yes/no

            // 13-14: Uploaded Document Paths
            // We use string columns to store the file path generated by Laravel's storage
            $table->string('cv_path'); 
            $table->string('uni_letter_path');
            
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('trainee_forms');
    }
};